#!/bin/sh

brew cask install android-studio
brew cask install atom
brew cask install eclipse-jee
brew cask install google-chrome
brew cask install java
brew cask install virtualbox
brew cask install virtualbox-extension-pack

