#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias vi="vim"

if [ -x "`which mvim`"  ];
then
  alias vim="mvim -v"
fi

function ssht() {
    if [ "$1" = "" ];
    then
      echo "Usage: $0 [host] [tmux-session]"
      return
    fi

    if [ "$2" != "" ];
    then
      TMUX_COMMAND=". /etc/profile; ; ~/.profile ; . ~/.zprofile; tmux new -A -s $2"
    fi

    echo "ssh $1 -t $TMUX_COMMAND"
    ssh $1 -t $TMUX_COMMAND
}

function lazygit() {
  git commit -a -m "$1"
  git push
}

alias hibernate='sudo pmset -a hibernatemode 25'
alias sleep='sudo pmset -a hibernatemode 0'
alias safesleep='sudo pmset -a hibernatemode 3'
alias smartsleep='sudo pmset -a hibernatemode 2'


export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
